# Generated by Django 3.1.4 on 2020-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20201210_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
